// String


let saudacao = "não contavam com minha astucia!"; // Declara e inicializa uma variável string
let numero = "2304" // Declara uma variável string chamada aString

let idade = "36"
let nome = "Jonathas"
let sobrenome = "Costa"


let frase = "estou aprendendo javaScript"
console.log(frase)

console.log(typeof nome)

//declare as sequintes variáveis

let nome1 = "Jonh"
let sobrenome1 = "Sabino"
let idade1 = 36
let cidade = "Fortaleza"
let profissao = "Desenvolvedor"

let frasecompleta = "Meu nome é " + nome1 + " " + sobrenome1 + ", tenho "+idade1+ " anos, moro em "+cidade+ " e sou " +profissao+ "."
console.log(frasecompleta)

let fraseElaborada = `Oi! me chamo ${nome1} ${sobrenome} sou muito dedicado e alegre tenho ${idade1} anos, resido na linda ${cidade} e a frase do dia é: ${saudacao}`
console.log(fraseElaborada)
